Repository Team-BC-1/gream-backend, pull requests merged in 2024-02, with the labels that each got.

#223 CQRS를 위한 @Transactional(readOnly) 에 따른 Secondary DB 매핑 처리
  src/main/java/bc1/gream/global/config/datasource/TransactionRoutingDataSource.java
  src/main/java/bc1/gream/global/config/datasource/TransactionRoutingDataSourceConfig.java
  src/main/resources/application.yml
Labels: improvement

#222 구매 입찰 기능 테스트 코드 추가
  src/main/java/bc1/gream/domain/buy/dto/response/BuyBidResponseDto.java
  src/test/java/bc1/gream/domain/buy/controller/BuyBidControllerTest.java
  src/test/java/bc1/gream/domain/buy/provider/BuyBidProviderTest.java
  src/test/java/bc1/gream/domain/buy/service/query/BuyQueryServiceTest.java
  src/test/java/bc1/gream/domain/order/validator/ProductValidatorTest.java
Labels: enhancement

#235 ProductService -> ProductCommandService, ProductQueryService 로 분리
  src/main/java/bc1/gream/domain/admin/controller/AdminController.java
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/main/java/bc1/gream/domain/product/provider/BuyOrderQueryProvider.java
  src/main/java/bc1/gream/domain/product/provider/SellOrderQueryProvider.java
  src/main/java/bc1/gream/domain/product/service/command/ProductCommandService.java
  src/main/java/bc1/gream/domain/product/service/query/ProductQueryService.java
  src/main/java/bc1/gream/domain/sell/provider/ProductOrderQueryProvider.java
  src/test/java/bc1/gream/domain/admin/controller/AdminControllerTest.java
  src/test/java/bc1/gream/domain/product/controller/query/ProductQueryControllerTest.java
  src/test/java/bc1/gream/domain/product/service/query/ProductQueryServiceTest.java
  src/test/java/bc1/gream/domain/product/service/query/impl/ProductOrderQueryProviderImplTest.java
Labels: bug

#190 토스 API 결제 처리
  build.gradle
  src/main/java/bc1/gream/domain/payment/toss/controller/TossPaymentController.java
  src/main/java/bc1/gream/domain/payment/toss/dto/request/TossPaymentInitialRequestDto.java
  src/main/java/bc1/gream/domain/payment/toss/dto/response/TossPaymentCardDto.java
  src/main/java/bc1/gream/domain/payment/toss/dto/response/TossPaymentFailResponseDto.java
  src/main/java/bc1/gream/domain/payment/toss/dto/response/TossPaymentInitialResponseDto.java
  src/main/java/bc1/gream/domain/payment/toss/dto/response/TossPaymentSuccessResponseDto.java
  src/main/java/bc1/gream/domain/payment/toss/entity/OrderName.java
  src/main/java/bc1/gream/domain/payment/toss/entity/PayType.java
  src/main/java/bc1/gream/domain/payment/toss/entity/TossPayment.java
  src/main/java/bc1/gream/domain/payment/toss/mapper/TossPaymentMapper.java
  src/main/java/bc1/gream/domain/payment/toss/repository/TossPaymentRepository.java
  src/main/java/bc1/gream/domain/payment/toss/service/TossPaymentService.java
  src/main/java/bc1/gream/domain/payment/toss/validator/TossPaymentRequestValidator.java
  src/main/java/bc1/gream/domain/user/entity/User.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/main/resources/application.yml
  src/test/java/bc1/gream/domain/payment/toss/controller/TossPaymentControllerTest.java
  src/test/java/bc1/gream/domain/payment/toss/mapper/TossPaymentMapperTest.java
  src/test/java/bc1/gream/domain/payment/toss/validator/TossPaymentRequestValidatorTest.java
  src/test/resources/application-test.yml
Labels: enhancement

#237 토스 API 호출 핸들러를 EventPublisher & Callback 을 통해 분리
  src/main/java/bc1/gream/domain/payment/toss/controller/TossPaymentController.java
  src/main/java/bc1/gream/domain/payment/toss/service/PaymentService.java
  src/main/java/bc1/gream/domain/payment/toss/service/event/TossPaymentEventListener.java
  src/main/java/bc1/gream/domain/payment/toss/service/event/TossPaymentSuccessCallback.java
  src/main/java/bc1/gream/domain/payment/toss/service/event/TossPaymentSuccessEvent.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/main/java/bc1/gream/global/config/AsyncConfig.java
  src/main/java/bc1/gream/global/exception/GlobalExceptionHandler.java
  src/test/java/bc1/gream/domain/payment/toss/controller/TossPaymentControllerTest.java
Labels: improvement

#225 ElastiCache 추가
  src/main/java/bc1/gream/global/redis/RedisConfig.java
  src/main/resources/application.yml
Labels: enhancement

#245 구매 관련 조회 테스트 추가
  src/main/java/bc1/gream/domain/buy/dto/response/BuyCheckOrderResponseDto.java
  src/test/java/bc1/gream/domain/buy/controller/UserBoughtHistoryControllerTest.java
Labels: test

#243 즉시 구매 테스트 코드 작성
  src/main/java/bc1/gream/domain/buy/dto/response/BuyCheckOrderResponseDto.java
  src/main/java/bc1/gream/domain/buy/dto/response/BuyNowResponseDto.java
  src/test/java/bc1/gream/domain/buy/controller/BuyNowControllerTest.java
  src/test/java/bc1/gream/domain/buy/controller/UserBoughtHistoryControllerTest.java
  src/test/java/bc1/gream/domain/buy/provider/BuyNowProviderTest.java
  src/test/java/bc1/gream/test/OrderTest.java
Labels: test

#257 기프티콘 관련 테스트 코드 추가
  src/test/java/bc1/gream/domain/gifticon/service/command/GifticonCommandServiceTest.java
  src/test/java/bc1/gream/domain/gifticon/service/query/GifticonQueryServiceTest.java
  src/test/java/bc1/gream/domain/order/service/command/OrderCommandServiceTest.java
  src/test/java/bc1/gream/domain/order/service/query/OrderQueryServiceTest.java
Labels: test

#255 관리자 관련 기능 테스트 코드 추가
  src/test/java/bc1/gream/domain/admin/controller/AdminControllerTest.java
  src/test/java/bc1/gream/domain/gifticon/service/command/GifticonCommandServiceTest.java
  src/test/java/bc1/gream/domain/gifticon/service/query/GifticonQueryServiceTest.java
  src/test/java/bc1/gream/domain/order/service/command/OrderCommandServiceTest.java
  src/test/java/bc1/gream/domain/order/service/query/OrderQueryServiceTest.java
  src/test/java/bc1/gream/test/RefundTest.java
Labels: test

#233 주문 시, 구매입찰/판매입찰 조회에 대한 PESSIMISTIC_WRITE 락 걸기
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/sell/dto/request/SellNowRequestDto.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImpl.java
  src/test/java/bc1/gream/concurrent/AsyncTransaction.java
  src/test/java/bc1/gream/concurrent/BuyBidSaveConcurrentTest.java
  src/test/java/bc1/gream/concurrent/BuyNowConcurrentTest.java
  src/test/java/bc1/gream/concurrent/SellNowConcurrentTest.java
  src/test/java/bc1/gream/domain/buy/provider/BuyBidProviderIntegrationTest.java
  src/test/java/bc1/gream/test/BaseIntegrationTest.java
  src/test/resources/application-test.yml
Labels: bug

#247 Buy 조회 시, 마감기한 이전의 데이터만을 조회
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustom.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/buy/service/query/BuyQueryService.java
  src/test/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/order/repository/BuyRepositoryTest.java
Labels: refactoring

#249 Sell 조회 시, 마감기한 이전의 데이터만을 조회
  src/main/java/bc1/gream/domain/sell/repository/SellRepository.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepositoryCustom.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/sell/service/query/SellQueryService.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryTest.java
Labels: refactoring

#252 TossPayments API 수정
  src/main/java/bc1/gream/domain/payment/toss/controller/TossPaymentController.java
  src/main/java/bc1/gream/domain/payment/toss/dto/request/TossPaymentInitialRequestDto.java
  src/main/java/bc1/gream/domain/payment/toss/dto/response/TossPaymentFailResponseDto.java
  src/main/java/bc1/gream/domain/payment/toss/dto/response/TossPaymentInitialResponseDto.java
  src/main/java/bc1/gream/domain/payment/toss/entity/TossPayment.java
  src/main/java/bc1/gream/domain/payment/toss/mapper/TossPaymentMapper.java
  src/main/java/bc1/gream/domain/payment/toss/repository/TossPaymentRepository.java
  src/main/java/bc1/gream/domain/payment/toss/service/PaymentService.java
  src/main/java/bc1/gream/domain/payment/toss/service/event/TossPaymentEventListener.java
  src/main/java/bc1/gream/domain/payment/toss/service/event/TossPaymentSuccessEvent.java
  src/main/java/bc1/gream/domain/payment/toss/validator/TossPaymentRequestValidator.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/test/java/bc1/gream/domain/payment/toss/controller/TossPaymentControllerTest.java
  src/test/java/bc1/gream/domain/payment/toss/mapper/TossPaymentMapperTest.java
  src/test/java/bc1/gream/domain/payment/toss/validator/TossPaymentRequestValidatorTest.java
Labels: bug

#261 어드민 상품 생성 시 이미지 추가
  src/main/java/bc1/gream/domain/admin/controller/AdminController.java
  src/main/java/bc1/gream/domain/admin/dto/request/AdminProductRequestDto.java
  src/main/java/bc1/gream/domain/product/service/command/ProductCommandService.java
Labels: enhancement

#264 README.md 추가
  README.md
Labels: documentation

#265 상품 거래 및 구매/판매 입찰 내역 조회 API 캐싱 처리
  src/main/java/bc1/gream/domain/buy/service/query/BuyQueryService.java
  src/main/java/bc1/gream/domain/product/service/query/ProductQueryService.java
  src/main/java/bc1/gream/domain/sell/service/query/SellQueryService.java
  src/main/java/bc1/gream/global/redis/RedisCacheName.java
  src/main/java/bc1/gream/global/redis/RedisConfig.java
  src/main/java/bc1/gream/global/redis/RestPage.java
  src/test/java/bc1/gream/domain/buy/service/query/BuyQueryServiceTest.java
Labels: enhancement

#267 상품 등록 API의 Content-Type 수정
  src/main/java/bc1/gream/domain/admin/controller/AdminController.java
  src/main/java/bc1/gream/global/security/WebSecurityConfig.java
Labels: bug

#269 [#268] fix : 트랜젝션 내에 유저 포인트 증가하도록 수정
  src/main/java/bc1/gream/domain/payment/toss/service/PaymentService.java
Labels: bug

#253 쿠폰 관련 테스트 코드 추가
  src/main/java/bc1/gream/domain/coupon/service/qeury/CouponQueryService.java
  src/test/java/bc1/gream/domain/admin/controller/AdminControllerTest.java
  src/test/java/bc1/gream/domain/buy/service/query/BuyQueryServiceTest.java
  src/test/java/bc1/gream/domain/coupon/controller/CouponControllerTest.java
  src/test/java/bc1/gream/domain/coupon/provider/CouponProviderTest.java
  src/test/java/bc1/gream/domain/coupon/service/qeury/CouponQueryServiceTest.java
  src/test/java/bc1/gream/domain/gifticon/service/command/GifticonCommandServiceTest.java
  src/test/java/bc1/gream/domain/gifticon/service/query/GifticonQueryServiceTest.java
  src/test/java/bc1/gream/domain/order/service/command/OrderCommandServiceTest.java
  src/test/java/bc1/gream/domain/order/service/query/OrderQueryServiceTest.java
  src/test/java/bc1/gream/domain/user/service/CouponQueryServiceTest.java
  src/test/java/bc1/gream/test/CouponTest.java
  src/test/java/bc1/gream/test/RefundTest.java
  src/test/java/bc1/gream/test/UserTest.java
Labels: test
