Repository Team-BC-1/gream-backend, pull requests merged in 2024-01, with the labels that each got.

#2 Feat/add global exception
  src/main/java/bc1/gream/global/common/ErrorResponseDto.java
  src/main/java/bc1/gream/global/common/RestResponse.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/main/java/bc1/gream/global/exception/GlobalException.java
  src/main/java/bc1/gream/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#6 Feat/add signup api
  src/main/java/bc1/gream/domain/user/controller/UserController.java
  src/main/java/bc1/gream/domain/user/dto/request/UserSignupRequestDto.java
  src/main/java/bc1/gream/domain/user/dto/response/UserSignupResponseDto.java
  src/main/java/bc1/gream/domain/user/entity/Provider.java
  src/main/java/bc1/gream/domain/user/entity/User.java
  src/main/java/bc1/gream/domain/user/entity/UserRole.java
  src/main/java/bc1/gream/domain/user/repository/UserRepository.java
  src/main/java/bc1/gream/domain/user/service/UserService.java
  src/main/java/bc1/gream/domain/user/service/impl/UserServiceImpl.java
  src/main/java/bc1/gream/global/common/InvalidInputMapper.java
  src/main/java/bc1/gream/global/common/InvalidInputResponseDto.java
  src/main/java/bc1/gream/global/exception/GlobalExceptionHandler.java
  src/main/java/bc1/gream/global/security/WebSecurityConfig.java
  src/main/resources/application.yml
  src/test/java/bc1/gream/.gitKeep
  src/test/java/bc1/gream/domain/user/service/impl/UserServiceImplTest.java
  src/test/java/bc1/gream/test/UserTest.java
  src/test/resources/application-test.yml
Labels: enhancement

#12 [#10] feat : test CI 생성
  .github/workflows/ci.yml
Labels: enhancement

#15 UserServiceImpl 을 주입받던 코드를 UserService 인터페이스로 수정
  src/main/java/bc1/gream/domain/user/controller/UserController.java
Labels: bug

#16 [#10] fix : gradle caching을 통한 발드 속도 향상 및 테스트 후 결과를 볼수있게 수정
  .github/workflows/ci.yml
Labels: enhancement

#26 Feat/add userdetails
  src/main/java/bc1/gream/domain/user/repository/UserRepository.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/main/java/bc1/gream/global/security/UserDetailsImpl.java
  src/main/java/bc1/gream/global/security/UserDetailsServiceImpl.java
Labels: enhancement

#24 판매 입찰 기능 구현
  src/main/java/bc1/gream/domain/product/entity/Product.java
  src/main/java/bc1/gream/domain/product/repository/ProductRepository.java
  src/main/java/bc1/gream/domain/product/service/ProductService.java
  src/main/java/bc1/gream/domain/sell/controller/SellController.java
  src/main/java/bc1/gream/domain/sell/dto/request/SellBidRequestDto.java
  src/main/java/bc1/gream/domain/sell/dto/response/SellBidResponseDto.java
  src/main/java/bc1/gream/domain/sell/entity/Sell.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepository.java
  src/main/java/bc1/gream/domain/sell/service/SellService.java
  src/main/java/bc1/gream/domain/sell/service/SellServiceMapper.java
  src/main/resources/images/images.png
  src/test/java/bc1/gream/domain/sell/service/SellServiceTest.java
  src/test/java/bc1/gream/test/ProductTest.java
  src/test/java/bc1/gream/test/SellTest.java
Labels: enhancement

#32 Feat/add jwt util
  src/main/java/bc1/gream/domain/user/dto/request/UserLoginRequestDto.java
  src/main/java/bc1/gream/domain/user/dto/response/UserLoginResponseDto.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/main/java/bc1/gream/global/jwt/JwtLoginFilter.java
  src/main/java/bc1/gream/global/jwt/JwtStatus.java
  src/main/java/bc1/gream/global/jwt/JwtUtil.java
  src/main/java/bc1/gream/global/redis/RedisConfig.java
  src/main/java/bc1/gream/global/redis/RedisUtil.java
  src/main/java/bc1/gream/global/security/UserDetailsServiceImpl.java
  src/main/java/bc1/gream/global/security/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#38 Feat/cancelbuybid
  .github/workflows/cicd.yml
  src/main/java/bc1/gream/domain/order/controller/BuyController.java
  src/main/java/bc1/gream/domain/order/controller/SellController.java
  src/main/java/bc1/gream/domain/order/dto/request/BuyBidRequestDto.java
  src/main/java/bc1/gream/domain/order/dto/request/BuyCancelBidRequestDto.java
  src/main/java/bc1/gream/domain/order/dto/request/SellBidRequestDto.java
  src/main/java/bc1/gream/domain/order/dto/request/SellCancelBidRequestDto.java
  src/main/java/bc1/gream/domain/order/dto/response/BuyBidResponseDto.java
  src/main/java/bc1/gream/domain/order/dto/response/BuyCancelBidResponseDto.java
  src/main/java/bc1/gream/domain/order/dto/response/SellBidResponseDto.java
  src/main/java/bc1/gream/domain/order/dto/response/SellCancelBidResponseDto.java
  src/main/java/bc1/gream/domain/order/entity/Buy.java
  src/main/java/bc1/gream/domain/order/entity/Sell.java
  src/main/java/bc1/gream/domain/order/repository/BuyRepository.java
  src/main/java/bc1/gream/domain/order/repository/SellRepository.java
  src/main/java/bc1/gream/domain/order/service/BuyService.java
  src/main/java/bc1/gream/domain/order/service/BuyServiceMapper.java
  src/main/java/bc1/gream/domain/order/service/SellService.java
  src/main/java/bc1/gream/domain/order/service/SellServiceMapper.java
  src/main/java/bc1/gream/domain/sell/service/SellService.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/test/java/bc1/gream/domain/order/service/BuyServiceTest.java
  src/test/java/bc1/gream/domain/order/service/SellServiceTest.java
  src/test/java/bc1/gream/test/BuyTest.java
  src/test/java/bc1/gream/test/SellTest.java
Labels: enhancement

#49 Feat/add logout api
  src/main/java/bc1/gream/domain/user/dto/response/UserLogoutResponseDto.java
  src/main/java/bc1/gream/global/security/LogoutHandlerImpl.java
  src/main/java/bc1/gream/global/security/LogoutSuccessHandlerImpl.java
  src/main/java/bc1/gream/global/security/WebSecurityConfig.java
Labels: enhancement

#42 판매입찰 / 구매입찰 내역 조회
  docs/jihoon/요구사항 체크리스트.md
  src/main/java/bc1/gream/domain/order/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/order/mapper/OrderMapper.java
  src/main/java/bc1/gream/domain/order/mapper/SellMapper.java
  src/main/java/bc1/gream/domain/order/repository/BuyRepository.java
  src/main/java/bc1/gream/domain/order/repository/BuyRepositoryCustom.java
  src/main/java/bc1/gream/domain/order/repository/BuyRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/order/repository/SellRepository.java
  src/main/java/bc1/gream/domain/order/repository/SellRepositoryCustom.java
  src/main/java/bc1/gream/domain/order/repository/SellRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/order/repository/helper/BuyQueryOrderFactory.java
  src/main/java/bc1/gream/domain/order/repository/helper/SellQueryOrderFactory.java
  src/main/java/bc1/gream/domain/order/service/BuyService.java
  src/main/java/bc1/gream/domain/order/service/BuyServiceMapper.java
  src/main/java/bc1/gream/domain/order/service/SellService.java
  src/main/java/bc1/gream/domain/order/service/SellServiceMapper.java
  src/main/java/bc1/gream/domain/order/service/query/OrderQueryService.java
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/main/java/bc1/gream/domain/product/dto/ProductCondition.java
  src/main/java/bc1/gream/domain/product/dto/TradeResponseDto.java
  src/main/java/bc1/gream/domain/product/repository/LikeProductRepository.java
  src/main/java/bc1/gream/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/bc1/gream/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/product/repository/helper/ProductQueryConditionFactory.java
  src/main/java/bc1/gream/domain/product/service/BuyOrderQueryService.java
  src/main/java/bc1/gream/domain/product/service/SellOrderQueryService.java
  src/main/java/bc1/gream/domain/product/service/query/ProductOrderQueryService.java
  src/main/java/bc1/gream/domain/product/service/query/ProductQueryService.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/main/java/bc1/gream/global/validator/OrderCriteriaValidator.java
  src/test/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/order/mapper/OrderMapperTest.java
  src/test/java/bc1/gream/domain/product/controller/query/ProductQueryControllerTest.java
  src/test/java/bc1/gream/domain/product/repository/ProductRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImplTest.java
  src/test/java/bc1/gream/global/validator/OrderCriteriaValidatorTest.java
Labels: enhancement

#47 Feat/gifticoncoupon
  src/main/java/bc1/gream/domain/common/facade/ChangeCouponStatusFacade.java
  src/main/java/bc1/gream/domain/common/model/BaseEntity.java
  src/main/java/bc1/gream/domain/order/controller/BuyController.java
  src/main/java/bc1/gream/domain/order/dto/request/BuyBidRequestDto.java
  src/main/java/bc1/gream/domain/order/entity/Buy.java
  src/main/java/bc1/gream/domain/order/entity/Gifticon.java
  src/main/java/bc1/gream/domain/order/entity/Order.java
  src/main/java/bc1/gream/domain/order/entity/Sell.java
  src/main/java/bc1/gream/domain/order/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/order/repository/GifticonRepository.java
  src/main/java/bc1/gream/domain/order/service/BuyService.java
  src/main/java/bc1/gream/domain/order/service/SellService.java
  src/main/java/bc1/gream/domain/product/entity/Product.java
  src/main/java/bc1/gream/domain/user/entity/Coupon.java
  src/main/java/bc1/gream/domain/user/entity/CouponStatus.java
  src/main/java/bc1/gream/domain/user/entity/DiscountType.java
  src/main/java/bc1/gream/domain/user/entity/User.java
  src/main/java/bc1/gream/domain/user/repository/CouponRepository.java
  src/main/java/bc1/gream/domain/user/service/CouponService.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/test/java/bc1/gream/domain/order/service/BuyServiceTest.java
  src/test/java/bc1/gream/domain/order/service/SellServiceTest.java
  src/test/java/bc1/gream/test/CouponTest.java
  src/test/java/bc1/gream/test/GifticonTest.java
  src/test/java/bc1/gream/test/SellTest.java
Labels: enhancement

#52 패키지 및 클래스명 재수정
  docs/jihoon/Todo-24-01-11(임시).md
  docs/jihoon/요구사항 체크리스트.md
  src/main/java/bc1/gream/domain/common/facade/BuyOrderQueryFacade.java
  src/main/java/bc1/gream/domain/common/facade/ProductOrderQueryFacade.java
  src/main/java/bc1/gream/domain/common/facade/SellOrderQueryFacade.java
  src/main/java/bc1/gream/domain/order/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/order/mapper/OrderMapper.java
  src/main/java/bc1/gream/domain/order/mapper/SellMapper.java
  src/main/java/bc1/gream/domain/product/controller/ProductLikeController.java
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/main/java/bc1/gream/domain/product/dto/response/ProductLikeResponseDto.java
  src/main/java/bc1/gream/domain/product/dto/response/ProductQueryResponseDto.java
  src/main/java/bc1/gream/domain/product/dto/response/TradeResponseDto.java
  src/main/java/bc1/gream/domain/product/dto/unit/ProductCondition.java
  src/main/java/bc1/gream/domain/product/mapper/ProductMapper.java
  src/main/java/bc1/gream/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/bc1/gream/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/product/service/ProductService.java
  src/main/java/bc1/gream/domain/product/service/query/ProductService.java
  src/main/java/bc1/gream/global/jpa/AuditingConfig.java
  src/test/java/bc1/gream/domain/order/mapper/OrderMapperTest.java
  src/test/java/bc1/gream/domain/product/controller/query/ProductQueryControllerTest.java
  src/test/java/bc1/gream/domain/product/mapper/ProductMapperTest.java
  src/test/java/bc1/gream/domain/product/repository/ProductRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/product/service/query/ProductQueryServiceTest.java
  src/test/java/bc1/gream/domain/product/service/query/impl/ProductOrderQueryFacadeImplTest.java
Labels: enhancement

#54 Feat/buynow
  src/main/java/bc1/gream/domain/common/facade/BuyOrderQueryFacade.java
  src/main/java/bc1/gream/domain/common/facade/ChangingCouponStatusFacade.java
  src/main/java/bc1/gream/domain/order/controller/BuyController.java
  src/main/java/bc1/gream/domain/order/dto/request/BuyNowRequestDto.java
  src/main/java/bc1/gream/domain/order/dto/response/BuyNowResponseDto.java
  src/main/java/bc1/gream/domain/order/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/order/mapper/OrderMapper.java
  src/main/java/bc1/gream/domain/order/repository/SellRepository.java
  src/main/java/bc1/gream/domain/order/service/BuyService.java
  src/main/java/bc1/gream/domain/user/entity/Coupon.java
  src/main/java/bc1/gream/domain/user/entity/DiscountType.java
  src/main/java/bc1/gream/domain/user/service/CouponService.java
  src/test/java/bc1/gream/domain/order/service/BuyServiceTest.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImplTest.java
  src/test/java/bc1/gream/test/BuyTest.java
  src/test/java/bc1/gream/test/CouponTest.java
  src/test/java/bc1/gream/test/SellTest.java
Labels: enhancement

#66 Feat/add frontend setting
  src/main/java/bc1/gream/global/common/RestResponse.java
  src/main/java/bc1/gream/global/exception/GlobalExceptionHandler.java
  src/main/java/bc1/gream/global/jwt/JwtLoginFilter.java
  src/main/java/bc1/gream/global/jwt/JwtUtil.java
  src/main/java/bc1/gream/global/security/WebSecurityConfig.java
Labels: enhancement

#68 Feat/fix error
  src/main/java/bc1/gream/domain/common/facade/ChangingCouponStatusFacade.java
  src/main/java/bc1/gream/domain/order/controller/BuyController.java
  src/main/java/bc1/gream/domain/order/dto/request/BuyBidRequestDto.java
  src/main/java/bc1/gream/domain/order/dto/request/BuyNowRequestDto.java
  src/main/java/bc1/gream/domain/order/dto/request/SellBidRequestDto.java
  src/main/java/bc1/gream/domain/order/dto/request/SellNowRequestDto.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/test/java/bc1/gream/test/GifticonTest.java
Labels: bug

#71 판매입찰 리팩토링
  docs/jihoon/요구사항 체크리스트.md
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepository.java
  src/main/java/bc1/gream/domain/gifticon/service/GifticonService.java
  src/main/java/bc1/gream/domain/order/controller/SellBidController.java
  src/main/java/bc1/gream/domain/order/controller/SellNowController.java
  src/main/java/bc1/gream/domain/order/entity/Gifticon.java
  src/main/java/bc1/gream/domain/order/entity/Order.java
  src/main/java/bc1/gream/domain/order/repository/SellRepository.java
  src/main/java/bc1/gream/domain/order/service/BuyService.java
  src/main/java/bc1/gream/domain/order/service/SellBidService.java
  src/main/java/bc1/gream/domain/order/service/SellNowService.java
  src/main/java/bc1/gream/domain/order/service/SellService.java
  src/main/java/bc1/gream/domain/order/service/command/OrderCommandService.java
  src/main/java/bc1/gream/domain/order/service/helper/coupon/CouponCalculator.java
  src/main/java/bc1/gream/domain/order/service/helper/deadline/Deadline.java
  src/main/java/bc1/gream/domain/order/service/helper/deadline/DeadlineCalculator.java
  src/main/java/bc1/gream/domain/order/validator/ProductValidator.java
  src/main/java/bc1/gream/domain/user/entity/DiscountType.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/test/java/bc1/gream/domain/order/service/BuyServiceTest.java
  src/test/java/bc1/gream/domain/order/service/SellBidServiceTest.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImplTest.java
Labels: enhancement

#74 로그인 성공 시 유저정보 응답하도록 수정
  src/main/java/bc1/gream/domain/user/dto/response/UserLoginResponseDto.java
  src/main/java/bc1/gream/global/jwt/JwtLoginFilter.java
Labels: enhancement

#76 상품 목록 조회 시 id도 함께 반환하도록 수정
  src/main/java/bc1/gream/domain/product/dto/response/ProductQueryResponseDto.java
Labels: enhancement

#69 즉시판매 리팩토링
  src/main/java/bc1/gream/domain/order/controller/SellNowController.java
  src/main/java/bc1/gream/domain/order/service/BuyService.java
  src/main/java/bc1/gream/domain/order/service/SellNowService.java
  src/main/java/bc1/gream/domain/order/service/helper/coupon/CouponCalculator.java
Labels: enhancement

#81 [TEST] TEST CASE VALUE 수정
  src/test/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImplTest.java
  src/test/java/bc1/gream/test/OrderTest.java
Labels: enhancement

#82 [FEAT] Coupon 기능 추가
  src/main/java/bc1/gream/domain/user/entity/DiscountType.java
  src/main/java/bc1/gream/domain/user/service/CouponService.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/test/java/bc1/gream/domain/user/service/CouponServiceTest.java
  src/test/java/bc1/gream/test/CouponTest.java
Labels: enhancement

#83 [FEAT] 쿠폰적용된 주문 발행 및 저장 시, 트랜잭션 사용하게끔 추가
  src/main/java/bc1/gream/domain/order/service/command/OrderCommandService.java
Labels: enhancement

#62 Github Actions + ECR + Auto Scaling Group + EC2 + CodeDeploy + S3 를 사용하여 Blue/Green CI/CD 구축하기 테스트
  .github/workflows/cd-v2.yml
  .github/workflows/cd.yml
  Dockerfile
  appspec.yml
  build.gradle
  deploy.sh
  src/main/java/bc1/gream/global/security/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#85 [TEST] 구매입찰 100개 동시요청
  src/test/java/bc1/gream/domain/order/repository/BuyRepositoryTest.java
  src/test/java/bc1/gream/domain/order/service/SellNowServiceIntegrationTest.java
  src/test/java/bc1/gream/domain/order/service/SellNowServiceTest.java
  src/test/java/bc1/gream/test/BaseIntegrationTest.java
Labels: enhancement

#84 [FIX] 가장 최근 Buy 조회 기능 구현
  src/main/java/bc1/gream/domain/order/repository/BuyRepository.java
  src/main/java/bc1/gream/domain/order/repository/BuyRepositoryCustom.java
  src/main/java/bc1/gream/domain/order/repository/BuyRepositoryCustomImpl.java
  src/test/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImplTest.java
Labels: bug

#97 [FIX] 가장 최근 Sell 조회 기능 수정
  src/main/java/bc1/gream/domain/order/repository/SellRepository.java
  src/main/java/bc1/gream/domain/order/repository/SellRepositoryCustom.java
  src/main/java/bc1/gream/domain/order/repository/SellRepositoryCustomImpl.java
  src/test/java/bc1/gream/domain/order/repository/SellRepositoryTest.java
Labels: bug

#94 [MOVE] Buy 도메인 분리
  src/main/java/bc1/gream/domain/buy/controller/BuyController.java
  src/main/java/bc1/gream/domain/buy/dto/request/BuyBidRequestDto.java
  src/main/java/bc1/gream/domain/buy/dto/request/BuyCancelBidRequestDto.java
  src/main/java/bc1/gream/domain/buy/dto/request/BuyNowRequestDto.java
  src/main/java/bc1/gream/domain/buy/dto/response/BuyBidResponseDto.java
  src/main/java/bc1/gream/domain/buy/dto/response/BuyCancelBidResponseDto.java
  src/main/java/bc1/gream/domain/buy/dto/response/BuyNowResponseDto.java
  src/main/java/bc1/gream/domain/buy/entity/Buy.java
  src/main/java/bc1/gream/domain/buy/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepository.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustom.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/buy/repository/helper/BuyQueryOrderFactory.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/common/facade/BuyOrderQueryFacade.java
  src/main/java/bc1/gream/domain/common/facade/ChangingCouponStatusFacade.java
  src/main/java/bc1/gream/domain/order/mapper/OrderMapper.java
  src/main/java/bc1/gream/domain/order/service/SellNowService.java
  src/main/java/bc1/gream/domain/order/service/command/OrderCommandService.java
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/test/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/order/repository/BuyRepositoryTest.java
  src/test/java/bc1/gream/domain/order/service/BuyServiceTest.java
  src/test/java/bc1/gream/domain/order/service/SellNowServiceIntegrationTest.java
  src/test/java/bc1/gream/domain/order/service/SellNowServiceTest.java
  src/test/java/bc1/gream/test/BaseIntegrationTest.java
  src/test/java/bc1/gream/test/BuyTest.java
Labels: enhancement

#98 [MOVE] Coupon 도메인 분리
  src/main/java/bc1/gream/domain/buy/controller/BuyController.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/common/facade/ChangingCouponStatusFacade.java
  src/main/java/bc1/gream/domain/order/service/command/OrderCommandService.java
  src/main/java/bc1/gream/domain/sell/service/SellNowService.java
  src/main/java/bc1/gream/domain/user/coupon/entity/Coupon.java
  src/main/java/bc1/gream/domain/user/coupon/entity/CouponStatus.java
  src/main/java/bc1/gream/domain/user/coupon/entity/DiscountType.java
  src/main/java/bc1/gream/domain/user/coupon/helper/CouponCalculator.java
  src/main/java/bc1/gream/domain/user/coupon/repository/CouponRepository.java
  src/main/java/bc1/gream/domain/user/service/CouponService.java
  src/test/java/bc1/gream/domain/order/repository/BuyRepositoryTest.java
  src/test/java/bc1/gream/domain/user/service/CouponServiceTest.java
  src/test/java/bc1/gream/test/BaseIntegrationTest.java
  src/test/java/bc1/gream/test/CouponTest.java
Labels: enhancement

#106 Sell 중간레이어 Transactional을 제거
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/gifticon/service/GifticonService.java
  src/main/java/bc1/gream/domain/order/service/command/OrderCommandService.java
  src/main/java/bc1/gream/domain/sell/service/SellBidService.java
  src/main/java/bc1/gream/domain/sell/service/SellNowService.java
  src/main/java/bc1/gream/domain/sell/service/SellService.java
  src/main/java/bc1/gream/domain/user/service/CouponService.java
Labels: refactoring

#109 반환값에 id 추가
  src/main/java/bc1/gream/domain/buy/controller/BuyController.java
  src/main/java/bc1/gream/domain/buy/dto/response/BuyCancelBidResponseDto.java
  src/main/java/bc1/gream/domain/buy/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/main/java/bc1/gream/domain/product/dto/response/TradeResponseDto.java
  src/main/java/bc1/gream/domain/sell/controller/SellBidController.java
  src/main/java/bc1/gream/domain/sell/dto/response/SellCancelBidResponseDto.java
  src/main/java/bc1/gream/domain/sell/service/SellBidService.java
Labels: enhancement

#111 각 API 별 반환 DTO 타입 변경
  src/main/java/bc1/gream/domain/buy/controller/BuyController.java
  src/main/java/bc1/gream/domain/buy/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/order/mapper/OrderMapper.java
  src/main/java/bc1/gream/domain/product/controller/ProductLikeController.java
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/main/java/bc1/gream/domain/product/controller/SellTradeResponseDto.java
  src/main/java/bc1/gream/domain/product/dto/response/BuyTradeResponseDto.java
  src/main/java/bc1/gream/domain/product/dto/response/OrderTradeResponseDto.java
  src/main/java/bc1/gream/domain/product/dto/response/ProductDetailsResponseDto.java
  src/main/java/bc1/gream/domain/product/dto/response/ProductDislikeResponseDto.java
  src/main/java/bc1/gream/domain/product/dto/response/ProductPreviewResponseDto.java
  src/main/java/bc1/gream/domain/product/mapper/ProductMapper.java
  src/main/java/bc1/gream/domain/sell/mapper/SellMapper.java
  src/test/java/bc1/gream/domain/order/mapper/OrderMapperTest.java
  src/test/java/bc1/gream/domain/product/mapper/ProductMapperTest.java
Labels: enhancement

#113 입찰 조회 시, 최근 입찰 순으로 조회 수정
  src/main/java/bc1/gream/domain/buy/repository/helper/BuyQueryOrderFactory.java
  src/main/java/bc1/gream/domain/sell/repository/helper/SellQueryOrderFactory.java
  src/test/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/buy/repository/helper/BuyQueryOrderFactoryTest.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/sell/repository/helper/SellQueryOrderFactoryTest.java
  src/test/java/bc1/gream/test/GifticonTest.java
Labels: enhancement

#115 체결거래내역 조회 시, 최근 순서대로 조회 기능
  src/main/java/bc1/gream/domain/common/model/BaseEntity.java
  src/main/java/bc1/gream/domain/order/entity/Order.java
  src/main/java/bc1/gream/domain/order/repository/OrderRepository.java
  src/main/java/bc1/gream/domain/order/service/query/OrderQueryService.java
  src/test/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/order/repository/OrderRepositoryTest.java
  src/test/java/bc1/gream/domain/order/service/query/OrderQueryServiceTest.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImplTest.java
Labels: enhancement

#121 Feat/buyseperate
  src/main/java/bc1/gream/domain/buy/controller/BuyBidCondtroller.java
  src/main/java/bc1/gream/domain/buy/controller/BuyController.java
  src/main/java/bc1/gream/domain/buy/controller/BuyNowController.java
  src/main/java/bc1/gream/domain/buy/service/BuyBidService.java
  src/main/java/bc1/gream/domain/buy/service/BuyNowService.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/common/facade/ChangingCouponStatusFacade.java
  src/main/java/bc1/gream/domain/user/service/CouponService.java
  src/test/java/bc1/gream/domain/order/service/BuyServiceTest.java
Labels: refactoring

#123 Feat/buyrefactor
  src/main/java/bc1/gream/domain/buy/controller/BuyBidCondtroller.java
  src/main/java/bc1/gream/domain/buy/provider/BuyBidProvider.java
  src/main/java/bc1/gream/domain/common/facade/ChangingCouponStatusFacade.java
  src/main/java/bc1/gream/domain/user/service/CouponService.java
Labels: refactoring

#127 Feat/cancelbuybidrefactor
  src/main/java/bc1/gream/domain/buy/controller/BuyNowController.java
  src/main/java/bc1/gream/domain/buy/provider/BuyBidProvider.java
  src/main/java/bc1/gream/domain/buy/provider/BuyNowProvider.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
Labels: refactoring

#128 사용자 구매한 기프티콘 조회
  src/main/java/bc1/gream/domain/buy/provider/BuyNowProvider.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/gifticon/mapper/GifticonMapper.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepository.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustom.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/gifticon/service/GifticonCommandService.java
  src/main/java/bc1/gream/domain/gifticon/service/GifticonQueryService.java
  src/main/java/bc1/gream/domain/order/entity/Gifticon.java
  src/main/java/bc1/gream/domain/sell/controller/SellBidController.java
  src/main/java/bc1/gream/domain/sell/controller/SellNowController.java
  src/main/java/bc1/gream/domain/sell/controller/UserSellHistoryController.java
  src/main/java/bc1/gream/domain/sell/dto/response/UserSoldGifticonResponseDto.java
  src/main/java/bc1/gream/domain/sell/entity/Sell.java
  src/main/java/bc1/gream/domain/sell/provider/SellBidProvider.java
  src/main/java/bc1/gream/domain/sell/provider/SellNowProvider.java
  src/main/java/bc1/gream/domain/sell/provider/UserSoldGifticonProvider.java
  src/test/java/bc1/gream/domain/gifticon/mapper/GifticonMapperTest.java
  src/test/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/sell/service/SellBidProviderTest.java
  src/test/java/bc1/gream/domain/sell/service/SellNowProviderIntegrationTest.java
  src/test/java/bc1/gream/domain/sell/service/SellNowProviderTest.java
  src/test/java/bc1/gream/test/BaseDataRepositoryTest.java
Labels: enhancement

#137 Feat/buynowrefactor
  src/main/java/bc1/gream/domain/buy/controller/BuyController.java
  src/main/java/bc1/gream/domain/buy/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/buy/provider/BuyBidProvider.java
  src/main/java/bc1/gream/domain/buy/provider/BuyNowProvider.java
  src/main/java/bc1/gream/domain/order/service/command/OrderCommandService.java
  src/main/java/bc1/gream/domain/sell/service/SellService.java
Labels: refactoring

#132 사용자 판매완료 내역 조회
  src/main/java/bc1/gream/domain/gifticon/mapper/GifticonMapper.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepository.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustom.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/gifticon/service/GifticonQueryService.java
  src/main/java/bc1/gream/domain/order/mapper/OrderMapper.java
  src/main/java/bc1/gream/domain/order/repository/OrderRepository.java
  src/main/java/bc1/gream/domain/order/service/query/OrderQueryService.java
  src/main/java/bc1/gream/domain/sell/controller/UserSellHistoryController.java
  src/main/java/bc1/gream/domain/sell/dto/response/OrderAsSellerResponseDto.java
  src/main/java/bc1/gream/domain/sell/dto/response/UserSoldGifticonResponseDto.java
  src/main/java/bc1/gream/domain/sell/provider/SellerOrderProvider.java
  src/test/java/bc1/gream/domain/gifticon/mapper/GifticonMapperTest.java
  src/test/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/order/mapper/OrderMapperTest.java
Labels: refactoring

#134 사용자가 판매자로서 현재 진행 중인 판매입찰 내역 조회
  src/main/java/bc1/gream/domain/sell/controller/UserSellHistoryController.java
  src/main/java/bc1/gream/domain/sell/dto/response/UserSellOnProgressResponseDto.java
  src/main/java/bc1/gream/domain/sell/mapper/SellMapper.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepository.java
  src/main/java/bc1/gream/domain/sell/service/SellService.java
  src/test/java/bc1/gream/domain/sell/mapper/SellMapperTest.java
Labels: enhancement

#136 판매입찰내역/구매입찰내역 조회 순서 및 매핑 정렬
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustom.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/buy/repository/helper/BuyQueryOrderFactory.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/main/java/bc1/gream/domain/product/dto/response/BuyPriceToQuantityResponseDto.java
  src/main/java/bc1/gream/domain/product/dto/response/SellPriceToQuantityResponseDto.java
  src/main/java/bc1/gream/domain/product/provider/BuyOrderQueryProvider.java
  src/main/java/bc1/gream/domain/product/provider/SellOrderQueryProvider.java
  src/main/java/bc1/gream/domain/sell/provider/ProductOrderQueryProvider.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepositoryCustom.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/sell/repository/helper/SellQueryOrderFactory.java
  src/main/java/bc1/gream/domain/sell/service/SellService.java
  src/test/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/buy/repository/helper/BuyQueryOrderFactoryTest.java
  src/test/java/bc1/gream/domain/product/controller/query/ProductQueryControllerTest.java
  src/test/java/bc1/gream/domain/product/service/query/impl/ProductOrderQueryProviderImplTest.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/sell/repository/helper/SellQueryOrderFactoryTest.java
  src/test/java/bc1/gream/test/BaseDataRepositoryTest.java
Labels: enhancement

#139 판매에 따른 사용자 포인트 충전 구현
  src/main/java/bc1/gream/domain/sell/provider/SellNowProvider.java
  src/main/java/bc1/gream/domain/user/entity/User.java
Labels: enhancement

#142 판매입찰 / 구매입찰 마감기한에 따른 삭제 스케줄러 구현
  build.gradle
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustom.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/buy/scheduler/BuyDeadlineScheduler.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepositoryCustom.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/sell/scheduler/SellDeadlineScheduler.java
  src/main/java/bc1/gream/domain/sell/service/SellService.java
  src/main/java/bc1/gream/global/config/BatchConfig.java
Labels: enhancement

#143 Feat/endhistory
  src/main/java/bc1/gream/domain/buy/controller/UserBoughtHistoryController.java
  src/main/java/bc1/gream/domain/buy/dto/request/BuyCheckOrderRequestDto.java
  src/main/java/bc1/gream/domain/buy/dto/response/BuyCheckOrderResponseDto.java
  src/main/java/bc1/gream/domain/gifticon/mapper/GifticonMapper.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustom.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/gifticon/service/GifticonQueryService.java
Labels: enhancement

#146 상품명에 따른 상품목록 조회
  src/main/java/bc1/gream/domain/product/dto/response/ProductPreviewByNameResponseDto.java
  src/main/java/bc1/gream/domain/product/mapper/ProductMapper.java
  src/main/java/bc1/gream/domain/product/repository/ProductRepository.java
  src/main/java/bc1/gream/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/product/service/query/ProductService.java
  src/test/java/bc1/gream/domain/product/repository/ProductRepositoryCustomImplTest.java
Labels: enhancement

#147 Feat/onprogresshsitory
  src/main/java/bc1/gream/domain/buy/controller/UserBoughtHistoryController.java
  src/main/java/bc1/gream/domain/buy/dto/request/BuyCheckBidRequestDto.java
  src/main/java/bc1/gream/domain/buy/dto/response/BuyCheckBidResponseDto.java
  src/main/java/bc1/gream/domain/buy/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustom.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
Labels: enhancement

#140 Feat/couponstatus
  src/main/java/bc1/gream/domain/buy/controller/BuyBidController.java
  src/main/java/bc1/gream/domain/buy/controller/BuyNowController.java
  src/main/java/bc1/gream/domain/buy/controller/UserBoughtHistoryController.java
  src/main/java/bc1/gream/domain/buy/dto/request/BuyCheckBidRequestDto.java
  src/main/java/bc1/gream/domain/buy/dto/request/BuyCheckOrderRequestDto.java
  src/main/java/bc1/gream/domain/buy/dto/response/BuyCheckBidResponseDto.java
  src/main/java/bc1/gream/domain/buy/dto/response/BuyCheckOrderResponseDto.java
  src/main/java/bc1/gream/domain/buy/mapper/BuyMapper.java
  src/main/java/bc1/gream/domain/buy/provider/BuyBidProvider.java
  src/main/java/bc1/gream/domain/buy/provider/BuyNowProvider.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustom.java
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/common/facade/ChangingCouponStatusFacade.java
  src/main/java/bc1/gream/domain/coupon/service/command/CouponCommandService.java
  src/main/java/bc1/gream/domain/coupon/service/qeury/CouponQueryService.java
  src/main/java/bc1/gream/domain/gifticon/mapper/GifticonMapper.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepository.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustom.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/gifticon/service/GifticonQueryService.java
  src/main/java/bc1/gream/domain/order/service/command/OrderCommandService.java
  src/main/java/bc1/gream/global/common/ResultCase.java
Labels: enhancement

#154 즉시 구매 / 구매 입찰 시 포인트 변경 기능 추가
  src/main/java/bc1/gream/domain/buy/provider/BuyBidProvider.java
  src/main/java/bc1/gream/domain/buy/provider/BuyNowProvider.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/user/entity/User.java
  src/main/java/bc1/gream/global/common/ResultCase.java
Labels: enhancement

#160 RepositoryCustomImpl leftjoin 이슈 해결
  src/main/java/bc1/gream/domain/buy/repository/BuyRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/coupon/repository/CouponRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImpl.java
Labels: bug

#158 즉시 판매 유스케이스 처리하는 경우 조회된 구매입찰의 쿠폰을 조회, 쿠폰의 상태를 변경
  src/main/java/bc1/gream/domain/sell/provider/SellNowProvider.java
Labels: enhancement

#155 상품 전체조회 시, 조건조회 가능하게끔 기능구현
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/main/java/bc1/gream/domain/sell/controller/UserSellHistoryController.java
  src/test/java/bc1/gream/domain/product/controller/query/ProductQueryControllerTest.java
Labels: enhancement

#163 Fix/buy now point
  src/main/java/bc1/gream/domain/buy/provider/BuyBidProvider.java
  src/main/java/bc1/gream/domain/buy/provider/BuyNowProvider.java
  src/main/java/bc1/gream/domain/buy/service/BuyService.java
  src/main/java/bc1/gream/domain/order/mapper/OrderMapper.java
  src/main/java/bc1/gream/domain/sell/dto/response/OrderAsSellerResponseDto.java
  src/main/java/bc1/gream/domain/sell/provider/SellNowProvider.java
  src/main/java/bc1/gream/domain/user/controller/UserController.java
  src/test/java/bc1/gream/domain/order/mapper/OrderMapperTest.java
Labels: refactoring

#164 전체 상품 조회 시, 브랜드와 상품명을 Query Parameter로 입력받기
  src/main/java/bc1/gream/domain/gifticon/entity/Gifticon.java
  src/main/java/bc1/gream/domain/gifticon/mapper/GifticonMapper.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepository.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustom.java
  src/main/java/bc1/gream/domain/gifticon/repository/GifticonRepositoryCustomImpl.java
  src/main/java/bc1/gream/domain/gifticon/service/GifticonCommandService.java
  src/main/java/bc1/gream/domain/gifticon/service/GifticonQueryService.java
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/main/java/bc1/gream/domain/product/repository/helper/ProductQueryConditionFactory.java
  src/main/java/bc1/gream/domain/sell/entity/Sell.java
  src/main/java/bc1/gream/domain/sell/provider/SellBidProvider.java
  src/main/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImpl.java
  src/test/java/bc1/gream/domain/product/controller/ProductQueryControllerIntegrationTest.java
  src/test/java/bc1/gream/domain/product/repository/helper/ProductQueryConditionFactoryTest.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryCustomImplTest.java
  src/test/java/bc1/gream/domain/sell/repository/SellRepositoryTest.java
  src/test/java/bc1/gream/domain/sell/service/SellNowProviderIntegrationTest.java
  src/test/java/bc1/gream/test/BaseDataRepositoryTest.java
  src/test/java/bc1/gream/test/BaseIntegrationTest.java
  src/test/java/bc1/gream/test/GifticonTest.java
  src/test/java/bc1/gream/test/ProductTest.java
Labels: bug

#169 [#168] feat : 관심상품 추가 서비스에 트랜젝션 어노테이션 추가
  src/main/java/bc1/gream/domain/product/service/command/ProductLikeService.java
Labels: bug

#171 로그인 성공 시 관심상품 id 리스트 응답
  src/main/java/bc1/gream/domain/user/dto/response/UserLoginResponseDto.java
  src/main/java/bc1/gream/domain/user/repository/UserRepository.java
  src/main/java/bc1/gream/global/jwt/JwtLoginFilter.java
  src/main/java/bc1/gream/global/security/WebSecurityConfig.java
Labels: enhancement

#174 script : application.yml << Server Timeout & Logging
  src/main/resources/application.yml
Labels: improvement

#176 중복된 관심상품 등록요청에 대한 검증처리
  src/main/java/bc1/gream/domain/product/controller/ProductLikeController.java
  src/main/java/bc1/gream/domain/product/dto/response/ProductLikesResponseDto.java
  src/main/java/bc1/gream/domain/product/entity/LikeProduct.java
  src/main/java/bc1/gream/domain/product/entity/Product.java
  src/main/java/bc1/gream/domain/product/service/command/ProductLikeService.java
  src/main/java/bc1/gream/domain/user/entity/User.java
  src/test/java/bc1/gream/domain/product/entity/LikeProductTest.java
  src/test/java/bc1/gream/domain/product/service/command/ProductLikeServiceIntegrationTest.java
  src/test/java/bc1/gream/domain/product/service/command/ProductLikeServiceTest.java
  src/test/java/bc1/gream/test/BaseDataRepositoryTest.java
  src/test/java/bc1/gream/test/BaseIntegrationTest.java
Labels: bug

#178 Swagger 토큰 생성 및 역할 문서화
  src/main/java/bc1/gream/domain/buy/controller/BuyBidController.java
  src/main/java/bc1/gream/domain/buy/controller/BuyNowController.java
  src/main/java/bc1/gream/domain/buy/controller/UserBoughtHistoryController.java
  src/main/java/bc1/gream/domain/coupon/controller/CouponController.java
  src/main/java/bc1/gream/domain/order/controller/OrderCommandController.java
  src/main/java/bc1/gream/domain/order/controller/OrderQueryController.java
  src/main/java/bc1/gream/domain/product/controller/ProductLikeController.java
  src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
  src/main/java/bc1/gream/domain/sell/controller/SellBidController.java
  src/main/java/bc1/gream/domain/sell/controller/SellNowController.java
  src/main/java/bc1/gream/domain/sell/controller/UserSellHistoryController.java
  src/main/java/bc1/gream/domain/user/controller/UserController.java
  src/main/java/bc1/gream/global/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: enhancement

#181 즉시 판매 및 판매 입찰에서 기프티콘 이미지를 받도록 수정
  build.gradle
  src/main/java/bc1/gream/domain/gifticon/entity/Gifticon.java
  src/main/java/bc1/gream/domain/sell/controller/SellBidController.java
  src/main/java/bc1/gream/domain/sell/controller/SellNowController.java
  src/main/java/bc1/gream/domain/sell/dto/request/SellBidRequestDto.java
  src/main/java/bc1/gream/domain/sell/dto/request/SellNowRequestDto.java
  src/main/java/bc1/gream/domain/sell/provider/SellBidProvider.java
  src/main/java/bc1/gream/domain/sell/provider/SellNowProvider.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/main/java/bc1/gream/infra/s3/S3Config.java
  src/main/java/bc1/gream/infra/s3/S3ImageService.java
  src/main/resources/application.yml
  src/test/java/bc1/gream/domain/sell/service/SellBidProviderTest.java
  src/test/java/bc1/gream/domain/sell/service/SellNowProviderIntegrationTest.java
  src/test/java/bc1/gream/test/GifticonTest.java
  src/test/resources/application-test.yml
Labels: enhancement

#189 관심상품 조회 API 만 수정
  src/main/java/bc1/gream/domain/product/dto/response/ProductLikesResponseDto.java
  src/main/java/bc1/gream/domain/product/mapper/ProductMapper.java
Labels: refactoring

#194 [#193] feat : 비밀번호 특수문자 중 ! 추가
  src/main/java/bc1/gream/domain/user/dto/request/UserSignupRequestDto.java
Labels: bug

#198 [#197] feat : 환급 엔티티 추가
  src/main/java/bc1/gream/domain/user/entity/Refund.java
Labels: enhancement

#200 환급 신청 리스트 조회 API 추가
  src/main/java/bc1/gream/domain/admin/controller/AdminController.java
  src/main/java/bc1/gream/domain/admin/dto/request/AdminGetRefundRequestDto.java
  src/main/java/bc1/gream/domain/admin/dto/response/AdminGetRefundResponseDto.java
  src/main/java/bc1/gream/domain/admin/mapper/RefundMapper.java
  src/main/java/bc1/gream/domain/user/repository/RefundRepository.java
  src/main/java/bc1/gream/domain/user/service/UserService.java
  src/main/java/bc1/gream/domain/user/service/query/RefundQueryService.java
  src/main/java/bc1/gream/global/security/WebSecurityConfig.java
Labels: enhancement

#202 관리자 상품 생성 api
  src/main/java/bc1/gream/domain/admin/controller/AdminController.java
  src/main/java/bc1/gream/domain/admin/dto/request/AdminProductRequestDto.java
  src/main/java/bc1/gream/domain/admin/dto/response/AdminProductResponseDto.java
  src/main/java/bc1/gream/domain/product/repository/ProductRepository.java
  src/main/java/bc1/gream/domain/product/service/query/ProductService.java
  src/main/java/bc1/gream/global/common/ResultCase.java
Labels: enhancement

#205 @Transactional(readOnly = true) 에 따라 Multi DataSource 매핑
  src/main/java/bc1/gream/global/config/datasource/DataSourceType.java
  src/main/java/bc1/gream/global/config/datasource/TransactionRoutingDataSource.java
  src/main/java/bc1/gream/global/config/datasource/TransactionRoutingDataSourceConfig.java
  src/main/resources/application.yml
  src/test/java/bc1/gream/global/config/datasource/TransactionRoutingDataSourceConfigTest.java
Labels: enhancement

#211 소셜 로그인 추가
  src/main/java/bc1/gream/domain/gifticon/entity/Gifticon.java
  src/main/java/bc1/gream/domain/user/entity/User.java
  src/main/java/bc1/gream/domain/user/repository/UserRepository.java
  src/main/java/bc1/gream/global/common/ResultCase.java
  src/main/java/bc1/gream/global/jwt/JwtAuthFilter.java
  src/main/java/bc1/gream/global/oauth/OAuth2Filter.java
  src/main/java/bc1/gream/global/oauth/OAuthAPIClient.java
  src/main/java/bc1/gream/global/oauth/OAuthInfoResponse.java
  src/main/java/bc1/gream/global/oauth/OAuthLoginParam.java
  src/main/java/bc1/gream/global/oauth/RequestOAuthInfoService.java
  src/main/java/bc1/gream/global/oauth/kakao/KakaoApiClient.java
  src/main/java/bc1/gream/global/oauth/kakao/KakaoInfoResponse.java
  src/main/java/bc1/gream/global/oauth/kakao/KakaoLoginParam.java
  src/main/java/bc1/gream/global/oauth/kakao/KakaoToken.java
  src/main/java/bc1/gream/global/redis/RedisConfig.java
  src/main/java/bc1/gream/global/resttemplate/RestTemplateConfig.java
  src/main/java/bc1/gream/global/security/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#203 어드민 쿠폰 생성 API
  src/main/java/bc1/gream/domain/admin/controller/AdminController.java
  src/main/java/bc1/gream/domain/admin/dto/request/AdminCreateCouponRequestDto.java
  src/main/java/bc1/gream/domain/admin/dto/response/AdminCreateCouponResponseDto.java
  src/main/java/bc1/gream/domain/coupon/entity/CouponStatus.java
  src/main/java/bc1/gream/domain/coupon/entity/DiscountType.java
  src/main/java/bc1/gream/domain/coupon/mapper/CouponMapper.java
  src/main/java/bc1/gream/domain/coupon/provider/CouponProvider.java
  src/main/java/bc1/gream/domain/coupon/service/command/CouponCommandService.java
  src/main/java/bc1/gream/global/exception/GlobalExceptionHandler.java
  src/test/java/bc1/gream/domain/admin/controller/AdminControllerTest.java
  src/test/java/bc1/gream/domain/coupon/mapper/CouponMapperTest.java
  src/test/java/bc1/gream/domain/coupon/service/command/CouponCommandServiceTest.java
  src/test/java/bc1/gream/global/security/WithMockCustomUser.java
  src/test/java/bc1/gream/global/security/WithMockCustomUserSecurityContextFactory.java
Labels: enhancement

#214 두 도메인에 만들어진 RefundMapper 통합
  src/main/java/bc1/gream/domain/admin/controller/AdminController.java
  src/main/java/bc1/gream/domain/admin/mapper/RefundMapper.java
  src/main/java/bc1/gream/domain/user/mapper/RefundMapper.java
Labels: bug

#215 CQRS 붙이기 이전으로 롤백처리
  src/main/java/bc1/gream/global/config/datasource/TransactionRoutingDataSource.java
  src/main/java/bc1/gream/global/config/datasource/TransactionRoutingDataSourceConfig.java
  src/main/resources/application.yml
  src/test/java/bc1/gream/global/config/datasource/TransactionRoutingDataSourceConfigTest.java
Labels: refactoring
